"use client";
import { useEffect, useMemo, useState } from "react";

type Menu={id:string;name:string;description:string;price:number;image:string;available:boolean;customizable:boolean};
type Opt={id:string;name:string;price:number;emoji:string;kind:"pasta"|"sauce"|"topping"|"cheese";available:boolean};
type Settings={brandName:string;heroTitle:string;heroSubtitle:string;whatsappNumber:string;currency:string;deliveryFee:number};
type Store={menu:Menu[];toppings:Opt[];settings:Settings};
type Draft={menuItemId:string;quantity:number;pastaId:string;sauceIds:string[];toppingIds:string[];cheeseIds:string[]};

const emptySettings:Settings={brandName:"Pastino",heroTitle:"Pasta made your way.",heroSubtitle:"Fresh pasta, built by you.",whatsappNumber:"",currency:"USD",deliveryFee:0};
function limits(name:string){const n=name.toLowerCase();return n.includes("signature")?{s:2,t:4}:n.includes("large")?{s:1,t:3}:{s:1,t:2}}

export default function Home(){
 const [store,setStore]=useState<Store>({menu:[],toppings:[],settings:emptySettings}),[loading,setLoading]=useState(true),[selected,setSelected]=useState<Menu|null>(null),[draft,setDraft]=useState<Draft|null>(null),[cart,setCart]=useState<Draft[]>([]),[type,setType]=useState("takeaway"),[name,setName]=useState(""),[phone,setPhone]=useState(""),[address,setAddress]=useState(""),[notes,setNotes]=useState(""),[sending,setSending]=useState(false),[error,setError]=useState("");
 useEffect(()=>{fetch("/api/storefront",{cache:"no-store"}).then(r=>r.json()).then(d=>{if(d.error)throw new Error(d.error);setStore(d)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 const byKind=(k:Opt["kind"])=>store.toppings.filter(o=>o.kind===k&&o.available);
 const itemById=useMemo(()=>new Map(store.menu.map(i=>[i.id,i])),[store.menu]); const optById=useMemo(()=>new Map(store.toppings.map(o=>[o.id,o])),[store.toppings]);
 function start(item:Menu){setSelected(item);setDraft({menuItemId:item.id,quantity:1,pastaId:"",sauceIds:[],toppingIds:[],cheeseIds:[]});setError("")}
 function toggle(field:"sauceIds"|"toppingIds"|"cheeseIds",id:string,max=99){if(!draft)return;const arr=draft[field];const next=arr.includes(id)?arr.filter(x=>x!==id):arr.length<max?[...arr,id]:arr;setDraft({...draft,[field]:next})}
 function add(){if(!draft||!selected)return;const l=limits(selected.name);if(selected.customizable&&(!draft.pastaId||draft.sauceIds.length!==l.s)){setError(`Choose 1 pasta and ${l.s} sauce${l.s>1?"s":""}.`);return}setCart(c=>[...c,draft]);setSelected(null);setDraft(null);setError("")}
 function linePrice(d:Draft){const item=itemById.get(d.menuItemId);if(!item)return 0;const ids=[d.pastaId,...d.sauceIds,...d.toppingIds,...d.cheeseIds];return (item.price+ids.reduce((s,id)=>s+(optById.get(id)?.price||0),0))*d.quantity}
 const subtotal=cart.reduce((s,c)=>s+linePrice(c),0),total=subtotal+(type==="delivery"?store.settings.deliveryFee:0);
 async function checkout(){setError("");if(!cart.length){setError("Your cart is empty.");return}setSending(true);try{const r=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderType:type,customerName:name,phone,address,notes,items:cart})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Order failed.");setCart([]);if(d.whatsappUrl)window.location.href=d.whatsappUrl;else alert(`Order ${d.orderNumber} received successfully.`)}catch(e){setError(e instanceof Error?e.message:"Order failed.")}finally{setSending(false)}}
 return <main><header className="nav"><a className="logo" href="#top">PASTINO<span>.</span></a><a className="navlink" href="#menu">Order online</a></header>
 <section id="top" className="hero"><div className="heroCopy"><div className="eyebrow">FRESH • FAST • YOUR WAY</div><h1>{store.settings.heroTitle}</h1><p>{store.settings.heroSubtitle}</p><a className="primary" href="#menu">Build your pasta →</a></div><div className="heroArt"><div className="stamp">PASTA<br/>MADE<br/>FRESH</div><div className="bowl">🍝</div></div></section>
 <section id="menu" className="section"><div className="sectionHead"><div><div className="eyebrow dark">THE MENU</div><h2>Choose your size.</h2></div><p>Pick the bowl, then make it completely yours.</p></div>{error&&<div className="error">{error}</div>}{loading?<div className="loading">Loading menu…</div>:<div className="cards">{store.menu.filter(i=>i.available).map(i=><article className="card" key={i.id}><div className="cardImg" style={{backgroundImage:`url(${i.image})`}}/><div className="cardBody"><div className="price">{store.settings.currency} {i.price.toFixed(2)}</div><h3>{i.name}</h3><p>{i.description}</p><button className="secondary" onClick={()=>start(i)}>Build this pasta</button></div></article>)}</div>}</section>
 <section className="checkout"><div className="cartPanel"><div className="eyebrow dark">YOUR ORDER</div><h2>{cart.length?`${cart.length} item${cart.length>1?"s":""} ready":"Your cart is waiting."}</h2>{cart.map((c,idx)=>{const item=itemById.get(c.menuItemId);const labels=[c.pastaId,...c.sauceIds,...c.toppingIds,...c.cheeseIds].map(id=>optById.get(id)?.name).filter(Boolean);return <div className="cartLine" key={idx}><div><b>{c.quantity}× {item?.name}</b><small>{labels.join(" · ")}</small></div><div><b>{store.settings.currency} {linePrice(c).toFixed(2)}</b><button onClick={()=>setCart(x=>x.filter((_,i)=>i!==idx))}>Remove</button></div></div>})}</div>
 <div className="checkoutForm"><div className="switch"><button className={type==="takeaway"?"active":""} onClick={()=>setType("takeaway")}>Takeaway</button><button className={type==="delivery"?"active":""} onClick={()=>setType("delivery")}>Delivery</button></div><div className="grid2"><input placeholder="Your name" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="Phone number" value={phone} onChange={e=>setPhone(e.target.value)}/></div>{type==="delivery"&&<input placeholder="Delivery address" value={address} onChange={e=>setAddress(e.target.value)}/>}<textarea placeholder="Notes (optional)" value={notes} onChange={e=>setNotes(e.target.value)}/><div className="total"><span>Total</span><b>{store.settings.currency} {total.toFixed(2)}</b></div><button className="primary full" disabled={sending} onClick={checkout}>{sending?"Sending order…":"Place order & continue to WhatsApp"}</button><small className="fine">Your order is saved to Pastino before WhatsApp opens.</small></div></section>
 <footer><b>PASTINO.</b><span>Fresh pasta. Built your way.</span></footer>
 {selected&&draft&&<div className="modalBack"><div className="modal"><button className="close" onClick={()=>setSelected(null)}>×</button><div className="eyebrow dark">BUILD YOUR BOWL</div><h2>{selected.name}</h2><p>{selected.description}</p><Choice title="1. Choose pasta" options={byKind("pasta")} selected={[draft.pastaId]} onClick={id=>setDraft({...draft,pastaId:id})}/><Choice title={`2. Choose ${limits(selected.name).s} sauce${limits(selected.name).s>1?"s":""}`} options={byKind("sauce")} selected={draft.sauceIds} onClick={id=>toggle("sauceIds",id,limits(selected.name).s)}/><Choice title={`3. Choose up to ${limits(selected.name).t} toppings`} options={byKind("topping")} selected={draft.toppingIds} onClick={id=>toggle("toppingIds",id,limits(selected.name).t)}/><Choice title="4. Add cheese" options={byKind("cheese")} selected={draft.cheeseIds} onClick={id=>toggle("cheeseIds",id)}/>{error&&<div className="error">{error}</div>}<button className="primary full" onClick={add}>Add to order</button></div></div>}
 </main>
}
function Choice({title,options,selected,onClick}:{title:string;options:Opt[];selected:string[];onClick:(id:string)=>void}){return <div className="choice"><h4>{title}</h4><div className="chips">{options.map(o=><button key={o.id} className={selected.includes(o.id)?"chip active":"chip"} onClick={()=>onClick(o.id)}>{o.emoji} {o.name}{o.price>0?` +$${o.price}`:""}</button>)}</div></div>}
