(() => { let password='', store=null; const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(url,opt={}){const r=await fetch('../api/'+url,{...opt,headers:{...(opt.headers||{}),'X-Admin-Password':password}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed.');return d} function msg(t,ok=false){$('message').innerHTML=t?`<div class="${ok?'notice':'error'}">${esc(t)}</div>`:''}
async function load(){try{password=$('password').value;sessionStorage.setItem('pastino-admin',password);store=await api('admin.php');$('adminContent').classList.remove('hidden');fillSettings();render();msg('')}catch(e){msg(e.message)}} function fillSettings(){for(const k of ['brandName','whatsappNumber','currency','deliveryFee','heroTitle','heroSubtitle'])$(k).value=store.settings[k]??''}
function render(){$('menuList').innerHTML=store.menu.map(x=>`<div class="adminRow"><img src="${esc(x.image||'https://placehold.co/100')}" alt=""><div><b>${esc(x.name)}</b><small>${esc(x.description)} · $${Number(x.price).toFixed(2)}</small></div><div class="rowActions"><button data-edit-item="${esc(x.id)}">Edit</button><button class="danger" data-del-item="${esc(x.id)}">Delete</button></div></div>`).join('');$('optionList').innerHTML=store.toppings.map(x=>`<div class="adminRow option"><div class="emoji">${esc(x.emoji)}</div><div><b>${esc(x.name)}</b><small>${esc(x.kind)} · $${Number(x.price).toFixed(2)}</small></div><div class="rowActions"><button data-edit-option="${esc(x.id)}">Edit</button><button class="danger" data-del-option="${esc(x.id)}">Delete</button></div></div>`).join('');document.querySelectorAll('[data-edit-item]').forEach(b=>b.onclick=()=>editItem(b.dataset.editItem));document.querySelectorAll('[data-del-item]').forEach(b=>b.onclick=()=>del('item',b.dataset.delItem));document.querySelectorAll('[data-edit-option]').forEach(b=>b.onclick=()=>editOption(b.dataset.editOption));document.querySelectorAll('[data-del-option]').forEach(b=>b.onclick=()=>del('option',b.dataset.delOption))}
function editItem(id){const x=store.menu.find(i=>i.id===id);$('itemId').value=x.id;$('itemName').value=x.name;$('itemPrice').value=x.price;$('itemDescription').value=x.description;$('itemImage').value=x.image;$('itemSort').value=x.sortOrder;$('itemAvailable').checked=x.available;$('itemCustomizable').checked=x.customizable;$('itemFormTitle').textContent='Edit item';window.scrollTo({top:$('itemFormTitle').offsetTop-80,behavior:'smooth'})} function editOption(id){const x=store.toppings.find(i=>i.id===id);$('optionId').value=x.id;$('optionName').value=x.name;$('optionPrice').value=x.price;$('optionEmoji').value=x.emoji;$('optionKind').value=x.kind;$('optionSort').value=x.sortOrder;$('optionAvailable').checked=x.available}
async function reload(){store=await api('admin.php');fillSettings();render()} async function del(kind,id){if(!confirm('Delete this item?'))return;try{await api(`admin.php?kind=${kind}&id=${encodeURIComponent(id)}`,{method:'DELETE'});await reload();msg('Deleted ✓',true)}catch(e){msg(e.message)}}
$('unlock').onclick=load;$('password').value=sessionStorage.getItem('pastino-admin')||'';$('saveSettings').onclick=async()=>{try{await api('admin.php',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({brandName:$('brandName').value,whatsappNumber:$('whatsappNumber').value,currency:$('currency').value,deliveryFee:Number($('deliveryFee').value),heroTitle:$('heroTitle').value,heroSubtitle:$('heroSubtitle').value})});await reload();msg('Settings saved ✓',true)}catch(e){msg(e.message)}};
$('saveItem').onclick=async()=>{try{await api('admin.php',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'item',id:$('itemId').value,name:$('itemName').value,price:Number($('itemPrice').value),description:$('itemDescription').value,image:$('itemImage').value,category:'Pasta',sortOrder:Number($('itemSort').value),available:$('itemAvailable').checked,customizable:$('itemCustomizable').checked})});await reload();for(const id of ['itemId','itemName','itemPrice','itemDescription','itemImage','itemSort'])$(id).value='';$('itemAvailable').checked=true;$('itemCustomizable').checked=true;$('itemFormTitle').textContent='Add item';msg('Menu item saved ✓',true)}catch(e){msg(e.message)}};
$('saveOption').onclick=async()=>{try{await api('admin.php',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'option',optionKind:$('optionKind').value,id:$('optionId').value,name:$('optionName').value,price:Number($('optionPrice').value),emoji:$('optionEmoji').value,sortOrder:Number($('optionSort').value),available:$('optionAvailable').checked})});await reload();for(const id of ['optionId','optionName','optionPrice','optionSort'])$(id).value='';$('optionEmoji').value='✦';$('optionAvailable').checked=true;msg('Option saved ✓',true)}catch(e){msg(e.message)}};
$('itemUpload').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;const fd=new FormData();fd.append('file',f);try{const d=await api('upload.php',{method:'POST',body:fd});$('itemImage').value=d.url;msg('Image uploaded ✓',true)}catch(err){msg(err.message)}};
})();
