import { ensureSchema, getStorefrontData, requireAdmin } from "@/lib/store";

function text(v:unknown,max=300){return typeof v==="string"?v.trim().slice(0,max):""} function num(v:unknown){const n=Number(v);return Number.isFinite(n)?n:0}
async function auth(request:Request){const a=await requireAdmin(request);return a.ok?null:Response.json({error:a.error},{status:a.status})}

export async function GET(request:Request){const denied=await auth(request);if(denied)return denied;return Response.json(await getStorefrontData(),{headers:{"Cache-Control":"no-store"}})}

export async function PATCH(request:Request){const denied=await auth(request);if(denied)return denied;try{const b=await request.json() as any;const db=await ensureSchema();const settings={brandName:text(b.brandName,80)||"Pastino",heroTitle:text(b.heroTitle,160)||"Pasta made your way.",heroSubtitle:text(b.heroSubtitle,400),whatsappNumber:text(b.whatsappNumber,40),currency:text(b.currency,12)||"USD",deliveryFee:Math.max(0,num(b.deliveryFee))};await db.prepare("UPDATE web_settings SET brand_name=?,hero_title=?,hero_subtitle=?,whatsapp_number=?,currency=?,delivery_fee=? WHERE id='default'").bind(settings.brandName,settings.heroTitle,settings.heroSubtitle,settings.whatsappNumber,settings.currency,settings.deliveryFee).run();return Response.json({ok:true,settings})}catch(e){return Response.json({error:e instanceof Error?e.message:"Unable to save settings."},{status:500})}}

export async function PUT(request:Request){const denied=await auth(request);if(denied)return denied;try{const b=await request.json() as any;const db=await ensureSchema();if(b.kind==="item"){const id=text(b.id,100)||`menu-${crypto.randomUUID().slice(0,8)}`;const name=text(b.name,100);if(name.length<2)return Response.json({error:"Item name is required."},{status:400});await db.prepare("INSERT INTO web_menu_items (id,name,description,price,image,category,available,customizable,sort_order) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,description=excluded.description,price=excluded.price,image=excluded.image,category=excluded.category,available=excluded.available,customizable=excluded.customizable,sort_order=excluded.sort_order").bind(id,name,text(b.description,300),Math.max(0,num(b.price)),text(b.image,1000),text(b.category,80)||"Pasta",b.available===false?0:1,b.customizable===false?0:1,Math.round(num(b.sortOrder))).run();return Response.json({ok:true,id})}
const kinds=["pasta","sauce","topping","cheese"];if(b.kind==="option"){const id=text(b.id,100)||`option-${crypto.randomUUID().slice(0,8)}`;const name=text(b.name,100),optionKind=kinds.includes(b.optionKind)?b.optionKind:"topping";if(name.length<2)return Response.json({error:"Option name is required."},{status:400});await db.prepare("INSERT INTO web_toppings (id,name,price,emoji,kind,available,sort_order) VALUES (?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,price=excluded.price,emoji=excluded.emoji,kind=excluded.kind,available=excluded.available,sort_order=excluded.sort_order").bind(id,name,Math.max(0,num(b.price)),text(b.emoji,12)||"✦",optionKind,b.available===false?0:1,Math.round(num(b.sortOrder))).run();return Response.json({ok:true,id})}return Response.json({error:"Unknown item type."},{status:400})}catch(e){return Response.json({error:e instanceof Error?e.message:"Unable to save item."},{status:500})}}

export async function DELETE(request:Request){const denied=await auth(request);if(denied)return denied;try{const url=new URL(request.url),kind=url.searchParams.get("kind"),id=text(url.searchParams.get("id"),100);if(!id)return Response.json({error:"Missing id."},{status:400});const db=await ensureSchema();if(kind==="item")await db.prepare("DELETE FROM web_menu_items WHERE id=?").bind(id).run();else if(kind==="option")await db.prepare("DELETE FROM web_toppings WHERE id=?").bind(id).run();else return Response.json({error:"Unknown item type."},{status:400});return Response.json({ok:true})}catch(e){return Response.json({error:e instanceof Error?e.message:"Unable to delete."},{status:500})}}
